[package]
name = "currency_rates"
version = "0.1.0"
authors = ["chriskarani"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.11"
tokio-core = "0.1"
futures = "0.1"